export const OPEN_SIDEBAR_ADD_PROJECT_REQUEST = "OPEN_SIDEBAR_ADD_PROJECT_REQUEST";
export const OPEN_SIDEBAR_ADD_PROJECT_SUCCESS = "OPEN_SIDEBAR_ADD_PROJECT_SUCCESS";
export const OPEN_SIDEBAR_ADD_PROJECT_FAILURE = "OPEN_SIDEBAR_ADD_PROJECT_FAILURE";

export const CLOSE_SIDEBAR_ADD_PROJECT_REQUEST = "CLOSE_SIDEBAR_ADD_PROJECT_REQUEST";
export const CLOSE_SIDEBAR_ADD_PROJECT_SUCCESS = "CLOSE_SIDEBAR_ADD_PROJECT_SUCCESS";
export const CLOSE_SIDEBAR_ADD_PROJECT_FAILURE = "CLOSE_SIDEBAR_ADD_PROJECT_FAILURE";

export const OPEN_SIDEBAR_DELETE_PROJECT_REQUEST = "OPEN_SIDEBAR_DELETE_PROJECT_REQUEST";
export const OPEN_SIDEBAR_DELETE_PROJECT_SUCCESS = "OPEN_SIDEBAR_DELETE_PROJECT_SUCCESS";
export const OPEN_SIDEBAR_DELETE_PROJECT_FAILURE = "OPEN_SIDEBAR_DELETE_PROJECT_FAILURE";

export const CLOSE_SIDEBAR_DELETE_PROJECT_REQUEST = "CLOSE_SIDEBAR_DELETE_PROJECT_REQUEST";
export const CLOSE_SIDEBAR_DELETE_PROJECT_SUCCESS = "CLOSE_SIDEBAR_DELETE_PROJECT_SUCCESS";
export const CLOSE_SIDEBAR_DELETE_PROJECT_FAILURE = "CLOSE_SIDEBAR_DELETE_PROJECT_FAILURE";